# Generated by Django 3.1.2 on 2020-11-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201104_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='description',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='login',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='web_address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='isPasswordKeptAsHash',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
