# Generated by Django 3.1.2 on 2020-11-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20201104_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.BinaryField(),
        ),
    ]
