# Generated by Django 3.1.3 on 2021-01-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20210127_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='blockadeTime',
            field=models.DateTimeField(null=True),
        ),
    ]
