# Generated by Django 3.1.3 on 2021-01-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20210127_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_password', models.CharField(max_length=256, null=True)),
                ('id_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='wallet.user')),
                ('id_password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.password')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='wallet.user')),
            ],
        ),
    ]
