# Generated by Django 3.1.3 on 2021-01-28 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_actionlogs_passwordhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordhistory',
            name='id_user',
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='id_password',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet.password'),
            preserve_default=False,
        ),
    ]
